import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const roboto = Roboto({ weight: "300", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className + " "}>
        <body className="flex flex-col h-screen">
          <Header />
          <main className="flex h-full pt-14">
            <Sidebar />
            <section className="w-full max-h-full overflow-y-auto">
              {children}
            </section>
          </main>
        </body>
    </html>
  );
}
